-- This CLP file was created using DB2LOOK Version "9.7" 
-- Timestamp: Thu 05 Apr 2012 03:56:42 PM IST
-- Database Name: OCM            
-- Database Manager Version: DB2/LINUX Version 9.7.4       
-- Database Codepage: 1208
-- Database Collating Sequence is: IDENTITY


CONNECT TO OCM;



------------------------------------
-- DDL Statements for TABLESPACES --
------------------------------------


CREATE LARGE TABLESPACE "SYSTOOLSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 AUTORESIZE YES 
	 INITIALSIZE 32 M 
	 MAXSIZE NONE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL IBMDEFAULTBP
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 NO FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY ON;


CREATE USER TEMPORARY TABLESPACE "SYSTOOLSTMPSPACE" IN DATABASE PARTITION GROUP IBMCATGROUP 
	 PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE 
	 EXTENTSIZE 4
	 PREFETCHSIZE AUTOMATIC
	 BUFFERPOOL IBMDEFAULTBP
	 OVERHEAD 7.500000
	 TRANSFERRATE 0.060000 
	 FILE SYSTEM CACHING  
	 DROPPED TABLE RECOVERY OFF;


-- Mimic tablespace

ALTER TABLESPACE SYSCATSPACE
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      NO FILE SYSTEM CACHING 
      AUTORESIZE YES 
      TRANSFERRATE 0.060000;


ALTER TABLESPACE TEMPSPACE1
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      FILE SYSTEM CACHING 
      TRANSFERRATE 0.060000;


ALTER TABLESPACE USERSPACE1
      PREFETCHSIZE AUTOMATIC
      OVERHEAD 7.500000
      NO FILE SYSTEM CACHING 
      AUTORESIZE YES 
      TRANSFERRATE 0.060000;




------------------------------------------------
-- DDL Statements for table "DB2INST1"."MEMBER"
------------------------------------------------
 

CREATE TABLE "DB2INST1"."MEMBER"  (
		  "USERID" VARCHAR(32) NOT NULL , 
		  "PASSWORD" VARCHAR(32) NOT NULL , 
		  "USERTYPE" CHAR(10) NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2INST1"."MEMBER"

ALTER TABLE "DB2INST1"."MEMBER" 
	ADD CONSTRAINT "CC1331923354813" PRIMARY KEY
		("USERID");



------------------------------------------------
-- DDL Statements for table "DB2INST1"."ARTICLE"
------------------------------------------------
 

CREATE TABLE "DB2INST1"."ARTICLE"  (
		  "ARTICLEID" VARCHAR(10) NOT NULL , 
		  "USERID" VARCHAR(32) NOT NULL , 
		  "TITLE" VARCHAR(100) , 
		  "CONTENT" VARCHAR(2500) , 
		  "DATE" DATE , 
		  "RATING" INTEGER , 
		  "TAGS" VARCHAR(100) , 
		  "APPROVALSTATUS" CHAR(5) NOT NULL WITH DEFAULT 'no' , 
		  "READCOUNT" INTEGER NOT NULL WITH DEFAULT 0 , 
		  "RATECOUNT" INTEGER WITH DEFAULT 0 )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2INST1"."ARTICLE"

ALTER TABLE "DB2INST1"."ARTICLE" 
	ADD CONSTRAINT "CC1332072397196" PRIMARY KEY
		("ARTICLEID");



------------------------------------------------
-- DDL Statements for table "DB2INST1"."COMMENT"
------------------------------------------------
 

CREATE TABLE "DB2INST1"."COMMENT"  (
		  "COMMENTID" VARCHAR(10) NOT NULL , 
		  "USERID" VARCHAR(32) NOT NULL , 
		  "ARTICLEID" VARCHAR(10) NOT NULL , 
		  "DATE" DATE NOT NULL , 
		  "CONTENT" VARCHAR(200) NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2INST1"."COMMENT"

ALTER TABLE "DB2INST1"."COMMENT" 
	ADD CONSTRAINT "CC1332073015835" PRIMARY KEY
		("COMMENTID");



------------------------------------------------
-- DDL Statements for table "DB2INST1"."ADMIN"
------------------------------------------------
 

CREATE TABLE "DB2INST1"."ADMIN"  (
		  "ADMINID" VARCHAR(32) NOT NULL , 
		  "PASSWORD" VARCHAR(32) NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2INST1"."ADMIN"

ALTER TABLE "DB2INST1"."ADMIN" 
	ADD CONSTRAINT "CC1332073326851" PRIMARY KEY
		("ADMINID");



------------------------------------------------
-- DDL Statements for table "DB2INST1"."FEEDBACK"
------------------------------------------------
 

CREATE TABLE "DB2INST1"."FEEDBACK"  (
		  "FEEDBACKID" VARCHAR(10) NOT NULL , 
		  "USERID" VARCHAR(32) NOT NULL , 
		  "DATE" DATE NOT NULL , 
		  "CONTENT" VARCHAR(500) NOT NULL , 
		  "SUBJECT" VARCHAR(50) )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2INST1"."FEEDBACK"

ALTER TABLE "DB2INST1"."FEEDBACK" 
	ADD CONSTRAINT "CC1332073426884" PRIMARY KEY
		("FEEDBACKID");



------------------------------------------------
-- DDL Statements for table "DB2INST1"."PROFILE"
------------------------------------------------
 

CREATE TABLE "DB2INST1"."PROFILE"  (
		  "PROFILEID" VARCHAR(10) NOT NULL , 
		  "USERID" VARCHAR(32) NOT NULL , 
		  "FNAME" CHAR(20) , 
		  "MNAME" CHAR(20) , 
		  "LNAME" CHAR(20) , 
		  "COLLEGEID" VARCHAR(20) NOT NULL , 
		  "EMAIL" VARCHAR(30) NOT NULL , 
		  "SEX" CHAR(10) NOT NULL , 
		  "MEMBERTYPE" CHAR(10) NOT NULL , 
		  "YEAROFSTUDY" VARCHAR(10) , 
		  "DEGREE" VARCHAR(10) , 
		  "DEPT" VARCHAR(20) , 
		  "QUAL" VARCHAR(20) , 
		  "SECQN" VARCHAR(50) NOT NULL , 
		  "SECANS" VARCHAR(50) NOT NULL )   
		 IN "USERSPACE1" ; 


-- DDL Statements for primary key on Table "DB2INST1"."PROFILE"

ALTER TABLE "DB2INST1"."PROFILE" 
	ADD CONSTRAINT "CC1332074293153" PRIMARY KEY
		("PROFILEID");


-- DDL Statements for unique constraints on Table "DB2INST1"."PROFILE"


ALTER TABLE "DB2INST1"."PROFILE" 
	ADD CONSTRAINT "CC1332074300730" UNIQUE
		("COLLEGEID");


-- DDL Statements for check constraints on Table "DB2INST1"."MEMBER"

ALTER TABLE "DB2INST1"."MEMBER" 
	ADD CONSTRAINT "CC1331923372408" CHECK 
		(USERTYPE in('regular','moderator'))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2INST1"."ARTICLE"

ALTER TABLE "DB2INST1"."ARTICLE" 
	ADD CONSTRAINT "CC1332072408882" FOREIGN KEY
		("USERID")
	REFERENCES "DB2INST1"."MEMBER"
		("USERID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2INST1"."COMMENT"

ALTER TABLE "DB2INST1"."COMMENT" 
	ADD CONSTRAINT "CC1332073020825" FOREIGN KEY
		("USERID")
	REFERENCES "DB2INST1"."MEMBER"
		("USERID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "DB2INST1"."COMMENT" 
	ADD CONSTRAINT "CC1332073049060" FOREIGN KEY
		("ARTICLEID")
	REFERENCES "DB2INST1"."ARTICLE"
		("ARTICLEID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2INST1"."FEEDBACK"

ALTER TABLE "DB2INST1"."FEEDBACK" 
	ADD CONSTRAINT "CC1332073431210" FOREIGN KEY
		("USERID")
	REFERENCES "DB2INST1"."MEMBER"
		("USERID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for foreign keys on Table "DB2INST1"."PROFILE"

ALTER TABLE "DB2INST1"."PROFILE" 
	ADD CONSTRAINT "CC1332074310036" FOREIGN KEY
		("USERID")
	REFERENCES "DB2INST1"."MEMBER"
		("USERID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "DB2INST1"."PROFILE"

ALTER TABLE "DB2INST1"."PROFILE" 
	ADD CONSTRAINT "CC1332074343465" CHECK 
		(MEMBERTYPE in('student','faculty'))
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

-- DDL Statements for check constraints on Table "DB2INST1"."PROFILE"

ALTER TABLE "DB2INST1"."PROFILE" 
	ADD CONSTRAINT "CC1332074388225" CHECK 
		(COLLEGEID like '315________')
	ENFORCED
	ENABLE QUERY OPTIMIZATION;







---------------------------------------
-- Authorization statement on table space 
---------------------------------------

 
GRANT USE OF TABLESPACE "SYSTOOLSTMPSPACE" TO  PUBLIC   ;

COMMIT WORK;

CONNECT RESET;

TERMINATE;

